services:
  - type: web
    name: portfolio-chatbot-backend
    runtime: python
    rootDir: src/components/chatbot/backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --max-requests 50 --max-requests-jitter 10 --preload
    autoDeploy: true
